NOTION_API_KEY = "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"
NOTION_DATABASE_ID = "1f872022-1e76-81f2-8248-e812a9295df0"
GEMINI_API_KEY = "AIzaSyCNzqrl_SK4Og1Y1QDZjHk8vuqHO-UUMYIM"
PYTHONPATH = "."