
[notion]
NOTION_API_KEY = "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"
NOTION_DATABASE_ID = "1f872022-1e76-81f2-8248-e812a9295df0"
Content_Samples_database_ID = "1fa720221e7681db9659e8b51df9ce88"
voice_guidlines_database_id = "1fa720221e768171b5bafcd88c0900e3"


PYTHONPATH = "."

[google]
GEMINI_API_KEY = "AIzaSyClEM_lyDJLU3TEt5DjvvDTxW_fKo3Jo7Q"

[openai]
API_KEY= "***REMOVED***"
